PressYourLuck/Controllers/AuditController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using PressYourLuck.Helpers;
using PressYourLuck.Models;
using Microsoft.EntityFrameworkCore;

namespace PressYourLuck.Controllers
{
    public class AuditController : Controller
    {
        private AuditContext _auditContext;

        public AuditController(AuditContext auditContext)
        {
            _auditContext = auditContext;
        }

        // GET action method for display a list of audit records, stored in reverse chronological
        [HttpGet("audit/{type?}")]
        public IActionResult Index(string type)
        {
            var audit = _auditContext.Audits.Include(m => m.AuditType).OrderByDescending(g => g.CreatedDate).ToList();
            string selectedType = HttpContext.Session.GetString("selected-type");

            if (type == null)
            {
                if (selectedType != null && selectedType != "All")
                {
                    type = selectedType;
                    audit = audit.Where(t => t.AuditType.Name == type).ToList();
                    HttpContext.Session.SetString("selected-type", type);
                }
                else
                {
                    audit = _auditContext.Audits.Include(m => m.AuditType).OrderByDescending(g => g.CreatedDate).ToList();
                    type = "All";
                    HttpContext.Session.SetString("selected-type", type);
                }
            }
            else
            {
                if (type == "All")
                {
                    audit = _auditContext.Audits.Include(m => m.AuditType).OrderByDescending(g => g.CreatedDate).ToList();
                    type = "All";
                    HttpContext.Session.SetString("selected-type", type);
                }
                else
                {
                    audit = audit.Where(t => t.AuditType.Name == type).ToList();
                    HttpContext.Session.SetString("selected-type", type);
                }
            }

            AuditViewModel viewModel = new AuditViewModel()
            {
                Audits = audit,
                ActiveType = type,
                AuditTypes = new string[] { "Cash In", "Cash Out", "Win", "Lose" }
            };

            return View(viewModel);
        }
    }
}

PressYourLuck/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using PressYourLuck.Helpers;
@{
    double totalCoin = CoinsHelper.GetTotalCoins(Context);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Press Your Luck</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Press Your Luck</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Audit" asp-action="Index">Audit</a>
                        </li>
                    </ul>
                </div>
                @if (CoinsHelper.GetTotalCoins(Context) != 0.0)
                {
                    <div class="nav-link">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                Total Coins: $@totalCoin.ToString("N2")
                            </li>
                        </ul>
                    </div>
                    <a asp-controller="Player" asp-action="CashOut" method="get" class="btn btn-success">Cash Out</a>
                }

            </div>
        </nav>
      
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData.Keys.Contains("message"))
            {
                <h4 class="bg-info text-white p-2">@TempData["message"]</h4>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PressYourLuck
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>